// Code generated by go generate. DO NOT EDIT.

package opt

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/subchanyayanbachtiar/algoliasearch-client-go/v3/algolia/opt"
)

func TestOffset(t *testing.T) {
	for _, c := range []struct {
		opts     []interface{}
		expected *opt.OffsetOption
	}{
		{
			opts:     []interface{}{nil},
			expected: opt.Offset(0),
		},
		{
			opts:     []interface{}{opt.Offset(0)},
			expected: opt.Offset(0),
		},
		{
			opts:     []interface{}{opt.Offset(1)},
			expected: opt.Offset(1),
		},
		{
			opts:     []interface{}{opt.Offset(-42)},
			expected: opt.Offset(-42),
		},
	} {
		var (
			in  = ExtractOffset(c.opts...)
			out opt.OffsetOption
		)
		data, err := json.Marshal(&in)
		require.NoError(t, err)
		err = json.Unmarshal(data, &out)
		require.NoError(t, err)
		require.Equal(t, *c.expected, out)
	}
}
