// Code generated by go generate. DO NOT EDIT.

package opt

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/subchanyayanbachtiar/algoliasearch-client-go/v3/algolia/opt"
)

func TestReplaceExistingSynonyms(t *testing.T) {
	for _, c := range []struct {
		opts     []interface{}
		expected *opt.ReplaceExistingSynonymsOption
	}{
		{
			opts:     []interface{}{nil},
			expected: opt.ReplaceExistingSynonyms(false),
		},
		{
			opts:     []interface{}{opt.ReplaceExistingSynonyms(true)},
			expected: opt.ReplaceExistingSynonyms(true),
		},
		{
			opts:     []interface{}{opt.ReplaceExistingSynonyms(false)},
			expected: opt.ReplaceExistingSynonyms(false),
		},
	} {
		var (
			in  = ExtractReplaceExistingSynonyms(c.opts...)
			out opt.ReplaceExistingSynonymsOption
		)
		data, err := json.Marshal(&in)
		require.NoError(t, err)
		err = json.Unmarshal(data, &out)
		require.NoError(t, err)
		require.Equal(t, *c.expected, out)
	}
}
